version: '3.4'

services:
  psp:
    container_name: psp
    networks: ['mindlogic-network']
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
     - './:/app/'
     - '/hdd3/taeho/dataset/:/data/'
     
networks: {mindlogic-network: {}}